export const countryList = {
  "": [
    {
      chineseName: "澳大利亚",
      chinesePhoneticize: "aodaliya",
      commonName: "Australia",
      disablePrefill: false,
      displayName: "澳大利亚",
      enable: true,
      formalName: "Commonwealth of Australia",
      id: "AU",
      localName: "",
      nationalFlag: "🇦🇺",
      startChar: "A",
      telephoneCode: "61",
    },
    {
      chineseName: "新西兰",
      chinesePhoneticize: "xinxilan",
      commonName: "New Zealand",
      disablePrefill: false,
      displayName: "新西兰",
      enable: true,
      formalName: "",
      id: "NZ",
      localName: "",
      nationalFlag: "🇳🇿",
      startChar: "N",
      telephoneCode: "64",
    },
  ],
  A: [
    {
      chineseName: "澳大利亚",
      chinesePhoneticize: "aodaliya",
      commonName: "Australia",
      disablePrefill: false,
      displayName: "澳大利亚",
      enable: true,
      formalName: "Commonwealth of Australia",
      id: "AU",
      localName: "",
      nationalFlag: "🇦🇺",
      startChar: "A",
      telephoneCode: "61",
    },
    {
      chineseName: "阿尔巴尼亚",
      chinesePhoneticize: "aerbaniya",
      commonName: "Albania",
      disablePrefill: false,
      displayName: "阿尔巴尼亚",
      enable: true,
      formalName: "Republic of Albania",
      id: "AL",
      localName: "",
      nationalFlag: "🇦🇱",
      startChar: "A",
      telephoneCode: "355",
    },
    {
      chineseName: "阿尔及利亚",
      chinesePhoneticize: "aerjiliya",
      commonName: "Algeria",
      disablePrefill: false,
      displayName: "阿尔及利亚",
      enable: true,
      formalName: "People's Democratic Republic of Algeria",
      id: "DZ",
      localName: "",
      nationalFlag: "🇩🇿",
      startChar: "A",
      telephoneCode: "213",
    },
    {
      chineseName: "阿富汗",
      chinesePhoneticize: "afuhan",
      commonName: "Afghanistan",
      disablePrefill: false,
      displayName: "阿富汗",
      enable: true,
      formalName: "Islamic State of Afghanistan",
      id: "AF",
      localName: "",
      nationalFlag: "🇦🇫",
      startChar: "A",
      telephoneCode: "93",
    },
    {
      chineseName: "阿根廷",
      chinesePhoneticize: "agenting",
      commonName: "Argentina",
      disablePrefill: false,
      displayName: "阿根廷",
      enable: true,
      formalName: "Argentine Republic",
      id: "AR",
      localName: "",
      nationalFlag: "🇦🇷",
      startChar: "A",
      telephoneCode: "54",
    },
    {
      chineseName: "爱尔兰",
      chinesePhoneticize: "aierlan",
      commonName: "Ireland",
      disablePrefill: false,
      displayName: "爱尔兰",
      enable: true,
      formalName: "",
      id: "IE",
      localName: "",
      nationalFlag: "🇮🇪",
      startChar: "I",
      telephoneCode: "353",
    },
    {
      chineseName: "埃及",
      chinesePhoneticize: "aiji",
      commonName: "Egypt",
      disablePrefill: false,
      displayName: "埃及",
      enable: true,
      formalName: "Arab Republic of Egypt",
      id: "EG",
      localName: "",
      nationalFlag: "🇪🇬",
      startChar: "E",
      telephoneCode: "20",
    },
    {
      chineseName: "埃塞俄比亚",
      chinesePhoneticize: "aisaiebiya",
      commonName: "Ethiopia",
      disablePrefill: false,
      displayName: "埃塞俄比亚",
      enable: true,
      formalName: "Federal Democratic Republic of Ethiopia",
      id: "ET",
      localName: "",
      nationalFlag: "🇪🇹",
      startChar: "E",
      telephoneCode: "251",
    },
    {
      chineseName: "爱沙尼亚",
      chinesePhoneticize: "aishaniya",
      commonName: "Estonia",
      disablePrefill: false,
      displayName: "爱沙尼亚",
      enable: true,
      formalName: "Republic of Estonia",
      id: "EE",
      localName: "",
      nationalFlag: "🇪🇪",
      startChar: "E",
      telephoneCode: "372",
    },
    {
      chineseName: "阿拉伯联合酋长国",
      chinesePhoneticize: "alabolianheqiuzhangguo",
      commonName: "United Arab Emirates",
      disablePrefill: false,
      displayName: "阿拉伯联合酋长国",
      enable: true,
      formalName: "United Arab Emirates",
      id: "AE",
      localName: "",
      nationalFlag: "🇦🇪",
      startChar: "U",
      telephoneCode: "971",
    },
    {
      chineseName: "阿鲁巴",
      chinesePhoneticize: "aluba",
      commonName: "Aruba",
      disablePrefill: false,
      displayName: "阿鲁巴",
      enable: true,
      formalName: "Aruba",
      id: "AW",
      localName: "",
      nationalFlag: "🇦🇼",
      startChar: "A",
      telephoneCode: "297",
    },
    {
      chineseName: "阿曼",
      chinesePhoneticize: "aman",
      commonName: "Oman",
      disablePrefill: false,
      displayName: "阿曼",
      enable: true,
      formalName: "Sultanate of Oman",
      id: "OM",
      localName: "",
      nationalFlag: "🇴🇲",
      startChar: "O",
      telephoneCode: "968",
    },
    {
      chineseName: "安道尔",
      chinesePhoneticize: "andaoer",
      commonName: "Andorra",
      disablePrefill: false,
      displayName: "安道尔",
      enable: true,
      formalName: "Principality of Andorra",
      id: "AD",
      localName: "",
      nationalFlag: "🇦🇩",
      startChar: "A",
      telephoneCode: "376",
    },
    {
      chineseName: "安哥拉",
      chinesePhoneticize: "angela",
      commonName: "Angola",
      disablePrefill: false,
      displayName: "安哥拉",
      enable: true,
      formalName: "Republic of Angola",
      id: "AO",
      localName: "",
      nationalFlag: "🇦🇴",
      startChar: "A",
      telephoneCode: "244",
    },
    {
      chineseName: "安圭拉",
      chinesePhoneticize: "anguila",
      commonName: "Anguilla",
      disablePrefill: false,
      displayName: "安圭拉",
      enable: true,
      formalName: "",
      id: "AI",
      localName: "",
      nationalFlag: "🇦🇮",
      startChar: "A",
      telephoneCode: "1264",
    },
    {
      chineseName: "安提瓜和巴布达",
      chinesePhoneticize: "antiguahebabuda",
      commonName: "Antigua and Barbuda",
      disablePrefill: false,
      displayName: "安提瓜和巴布达",
      enable: true,
      formalName: "",
      id: "AG",
      localName: "",
      nationalFlag: "🇦🇬",
      startChar: "A",
      telephoneCode: "1268",
    },
    {
      chineseName: "奥地利",
      chinesePhoneticize: "aodili",
      commonName: "Austria",
      disablePrefill: false,
      displayName: "奥地利",
      enable: true,
      formalName: "Republic of Austria",
      id: "AT",
      localName: "",
      nationalFlag: "🇦🇹",
      startChar: "A",
      telephoneCode: "43",
    },
    {
      chineseName: "澳门",
      chinesePhoneticize: "aomen",
      commonName: "Macau",
      disablePrefill: false,
      displayName: "中国澳门",
      enable: true,
      formalName: "Macau&nbsp;Special&nbsp;Administrative&nbsp;Region",
      id: "MO",
      localName: "",
      nationalFlag: "🇲🇴",
      startChar: "M",
      telephoneCode: "853",
    },
    {
      chineseName: "阿塞拜疆",
      chinesePhoneticize: "asaibaijiang",
      commonName: "Azerbaijan",
      disablePrefill: false,
      displayName: "阿塞拜疆",
      enable: true,
      formalName: "Republic of Azerbaijan",
      id: "AZ",
      localName: "",
      nationalFlag: "🇦🇿",
      startChar: "A",
      telephoneCode: "994",
    },
  ],
  B: [
    {
      chineseName: "巴巴多斯",
      chinesePhoneticize: "babaduosi",
      commonName: "Barbados",
      disablePrefill: false,
      displayName: "巴巴多斯",
      enable: true,
      formalName: "",
      id: "BB",
      localName: "",
      nationalFlag: "🇧🇧",
      startChar: "B",
      telephoneCode: "1246",
    },
    {
      chineseName: "巴布亚新几内亚",
      chinesePhoneticize: "babuyaxinjineiya",
      commonName: "Papua New Guinea",
      disablePrefill: false,
      displayName: "巴布亚新几内亚",
      enable: true,
      formalName: "Independent State of Papua New Guinea",
      id: "PG",
      localName: "",
      nationalFlag: "🇵🇬",
      startChar: "P",
      telephoneCode: "675",
    },
    {
      chineseName: "巴哈马",
      chinesePhoneticize: "bahama",
      commonName: "Bahamas",
      disablePrefill: false,
      displayName: "巴哈马",
      enable: true,
      formalName: "Commonwealth of The Bahamas",
      id: "BS",
      localName: "",
      nationalFlag: "🇧🇸",
      startChar: "B",
      telephoneCode: "1242",
    },
    {
      chineseName: "白俄罗斯",
      chinesePhoneticize: "baieluosi",
      commonName: "Belarus",
      disablePrefill: false,
      displayName: "白俄罗斯",
      enable: true,
      formalName: "Republic&nbsp;of&nbsp;Belarus",
      id: "BY",
      localName: "",
      nationalFlag: "🇧🇾",
      startChar: "B",
      telephoneCode: "375",
    },
    {
      chineseName: "百慕大",
      chinesePhoneticize: "baimuda",
      commonName: "Bermuda",
      disablePrefill: false,
      displayName: "百慕大",
      enable: true,
      formalName: "",
      id: "BM",
      localName: "",
      nationalFlag: "🇧🇲",
      startChar: "B",
      telephoneCode: "1441",
    },
    {
      chineseName: "巴基斯坦",
      chinesePhoneticize: "bajisitan",
      commonName: "Pakistan",
      disablePrefill: false,
      displayName: "巴基斯坦",
      enable: true,
      formalName: "Islamic Republic of Pakistan",
      id: "PK",
      localName: "",
      nationalFlag: "🇵🇰",
      startChar: "P",
      telephoneCode: "92",
    },
    {
      chineseName: "巴拉圭",
      chinesePhoneticize: "balagui",
      commonName: "Paraguay",
      disablePrefill: false,
      displayName: "巴拉圭",
      enable: true,
      formalName: "Republic of Paraguay",
      id: "PY",
      localName: "",
      nationalFlag: "🇵🇾",
      startChar: "P",
      telephoneCode: "595",
    },
    {
      chineseName: "巴勒斯坦",
      chinesePhoneticize: "balesitan",
      commonName: "Palestine",
      disablePrefill: false,
      displayName: "巴勒斯坦",
      enable: true,
      formalName: "State of Palestine",
      id: "PS",
      localName: "",
      nationalFlag: "🇵🇸",
      startChar: "P",
      telephoneCode: "970",
    },
    {
      chineseName: "巴林",
      chinesePhoneticize: "balin",
      commonName: "Bahrain",
      disablePrefill: false,
      displayName: "巴林",
      enable: true,
      formalName: "Kingdom of Bahrain",
      id: "BH",
      localName: "",
      nationalFlag: "🇧🇭",
      startChar: "B",
      telephoneCode: "973",
    },
    {
      chineseName: "巴拿马",
      chinesePhoneticize: "banama",
      commonName: "Panama",
      disablePrefill: false,
      displayName: "巴拿马",
      enable: true,
      formalName: "Republic of Panama",
      id: "PA",
      localName: "",
      nationalFlag: "🇵🇦",
      startChar: "P",
      telephoneCode: "507",
    },
    {
      chineseName: "保加利亚",
      chinesePhoneticize: "baojialiya",
      commonName: "Bulgaria",
      disablePrefill: false,
      displayName: "保加利亚",
      enable: true,
      formalName: "Republic of Bulgaria",
      id: "BG",
      localName: "",
      nationalFlag: "🇧🇬",
      startChar: "B",
      telephoneCode: "359",
    },
    {
      chineseName: "巴西",
      chinesePhoneticize: "baxi",
      commonName: "Brazil",
      disablePrefill: false,
      displayName: "巴西",
      enable: true,
      formalName: "Federative Republic of Brazil",
      id: "BR",
      localName: "",
      nationalFlag: "🇧🇷",
      startChar: "B",
      telephoneCode: "55",
    },
    {
      chineseName: "贝宁",
      chinesePhoneticize: "beining",
      commonName: "Benin",
      disablePrefill: false,
      displayName: "贝宁",
      enable: true,
      formalName: "Republic of Benin",
      id: "BJ",
      localName: "",
      nationalFlag: "🇧🇯",
      startChar: "B",
      telephoneCode: "229",
    },
    {
      chineseName: "比利时",
      chinesePhoneticize: "bilishi",
      commonName: "Belgium",
      disablePrefill: false,
      displayName: "比利时",
      enable: true,
      formalName: "Kingdom of Belgium",
      id: "BE",
      localName: "",
      nationalFlag: "🇧🇪",
      startChar: "B",
      telephoneCode: "32",
    },
    {
      chineseName: "冰岛",
      chinesePhoneticize: "bingdao",
      commonName: "Iceland",
      disablePrefill: false,
      displayName: "冰岛",
      enable: true,
      formalName: "Republic of Iceland",
      id: "IS",
      localName: "",
      nationalFlag: "🇮🇸",
      startChar: "I",
      telephoneCode: "354",
    },
    {
      chineseName: "博茨瓦纳",
      chinesePhoneticize: "bociwana",
      commonName: "Botswana",
      disablePrefill: false,
      displayName: "博茨瓦纳",
      enable: true,
      formalName: "Republic of Botswana",
      id: "BW",
      localName: "",
      nationalFlag: "🇧🇼",
      startChar: "B",
      telephoneCode: "267",
    },
    {
      chineseName: "波多黎各",
      chinesePhoneticize: "boduolige",
      commonName: "Puerto Rico",
      disablePrefill: false,
      displayName: "波多黎各",
      enable: true,
      formalName: "Puerto Rico",
      id: "PR",
      localName: "",
      nationalFlag: "🇵🇷",
      startChar: "P",
      telephoneCode: "1",
    },
    {
      chineseName: "波兰",
      chinesePhoneticize: "bolan",
      commonName: "Poland",
      disablePrefill: false,
      displayName: "波兰",
      enable: true,
      formalName: "Republic of Poland",
      id: "PL",
      localName: "",
      nationalFlag: "🇵🇱",
      startChar: "P",
      telephoneCode: "48",
    },
    {
      chineseName: "玻利维亚",
      chinesePhoneticize: "boliweiya",
      commonName: "Bolivia",
      disablePrefill: false,
      displayName: "玻利维亚",
      enable: true,
      formalName: "Republic of Bolivia",
      id: "BO",
      localName: "",
      nationalFlag: "🇧🇴",
      startChar: "B",
      telephoneCode: "591",
    },
    {
      chineseName: "伯利兹",
      chinesePhoneticize: "bolizi",
      commonName: "Belize",
      disablePrefill: false,
      displayName: "伯利兹",
      enable: true,
      formalName: "",
      id: "BZ",
      localName: "",
      nationalFlag: "🇧🇿",
      startChar: "B",
      telephoneCode: "501",
    },
    {
      chineseName: "波斯尼亚和黑塞哥维那 (波黑)",
      chinesePhoneticize: "bosiniyaheheisaigeweina (bohei)",
      commonName: "Bosnia and Herzegovina",
      disablePrefill: false,
      displayName: "波斯尼亚和黑塞哥维那 (波黑)",
      enable: true,
      formalName: "Bosnia&nbsp;and&nbsp;Herzegovina",
      id: "BA",
      localName: "",
      nationalFlag: "🇧🇦",
      startChar: "B",
      telephoneCode: "387",
    },
    {
      chineseName: "不丹",
      chinesePhoneticize: "budan",
      commonName: "Bhutan",
      disablePrefill: false,
      displayName: "不丹",
      enable: true,
      formalName: "Kingdom of Bhutan",
      id: "BT",
      localName: "",
      nationalFlag: "🇧🇹",
      startChar: "B",
      telephoneCode: "975",
    },
    {
      chineseName: "布基纳法索",
      chinesePhoneticize: "bujinafasuo",
      commonName: "Burkina Faso",
      disablePrefill: false,
      displayName: "布基纳法索",
      enable: true,
      formalName: "",
      id: "BF",
      localName: "",
      nationalFlag: "🇧🇫",
      startChar: "B",
      telephoneCode: "226",
    },
    {
      chineseName: "布隆迪",
      chinesePhoneticize: "bulongdi",
      commonName: "Burundi",
      disablePrefill: false,
      displayName: "布隆迪",
      enable: true,
      formalName: "Republic&nbsp;of&nbsp;Burundi",
      id: "BI",
      localName: "",
      nationalFlag: "🇧🇮",
      startChar: "B",
      telephoneCode: "257",
    },
  ],
  C: [
    {
      chineseName: "朝鲜",
      chinesePhoneticize: "chaoxian",
      commonName: "North Korea",
      disablePrefill: false,
      displayName: "朝鲜",
      enable: false,
      formalName: "Democratic People's Republic of Korea",
      id: "KP",
      localName: "",
      nationalFlag: "🇰🇵",
      startChar: "N",
      telephoneCode: "850",
    },
    {
      chineseName: "赤道几内亚",
      chinesePhoneticize: "chidaojineiya",
      commonName: "Equatorial Guinea",
      disablePrefill: false,
      displayName: "赤道几内亚",
      enable: true,
      formalName: "Republic of Equatorial Guinea",
      id: "GQ",
      localName: "",
      nationalFlag: "🇬🇶",
      startChar: "E",
      telephoneCode: "240",
    },
  ],
  D: [
    {
      chineseName: "丹麦",
      chinesePhoneticize: "danmai",
      commonName: "Denmark",
      disablePrefill: false,
      displayName: "丹麦",
      enable: true,
      formalName: "Kingdom of Denmark",
      id: "DK",
      localName: "",
      nationalFlag: "🇩🇰",
      startChar: "D",
      telephoneCode: "45",
    },
    {
      chineseName: "德国",
      chinesePhoneticize: "deguo",
      commonName: "Germany",
      disablePrefill: false,
      displayName: "德国",
      enable: true,
      formalName: "Federal Republic of Germany",
      id: "DE",
      localName: "",
      nationalFlag: "🇩🇪",
      startChar: "G",
      telephoneCode: "49",
    },
    {
      chineseName: "东帝汶",
      chinesePhoneticize: "dongdiwen",
      commonName: "Timor-Leste (East Timor)",
      disablePrefill: false,
      displayName: "东帝汶",
      enable: true,
      formalName: "Democratic Republic of Timor-Leste",
      id: "TL",
      localName: "",
      nationalFlag: "🇹🇱",
      startChar: "T",
      telephoneCode: "670",
    },
    {
      chineseName: "多哥",
      chinesePhoneticize: "duoge",
      commonName: "Togo",
      disablePrefill: false,
      displayName: "多哥",
      enable: true,
      formalName: "Togolese Republic",
      id: "TG",
      localName: "",
      nationalFlag: "🇹🇬",
      startChar: "T",
      telephoneCode: "228",
    },
    {
      chineseName: "多明尼加共和国",
      chinesePhoneticize: "duomingnijiagongheguo",
      commonName: "Dominican Republic",
      disablePrefill: false,
      displayName: "多明尼加共和国",
      enable: true,
      formalName: "",
      id: "DO",
      localName: "",
      nationalFlag: "🇩🇴",
      startChar: "D",
      telephoneCode: "1829",
    },
    {
      chineseName: "多明尼加共和国",
      chinesePhoneticize: "duomingnijiagongheguo",
      commonName: "Dominican Republic",
      disablePrefill: false,
      displayName: "多明尼加共和国",
      enable: true,
      formalName: "",
      id: "DO",
      localName: "",
      nationalFlag: "🇩🇴",
      startChar: "D",
      telephoneCode: "1809",
    },
    {
      chineseName: "多明尼加共和国",
      chinesePhoneticize: "duomingnijiagongheguo",
      commonName: "Dominican Republic",
      disablePrefill: false,
      displayName: "多明尼加共和国",
      enable: true,
      formalName: "",
      id: "DO",
      localName: "",
      nationalFlag: "🇩🇴",
      startChar: "D",
      telephoneCode: "1849",
    },
    {
      chineseName: "多米尼克",
      chinesePhoneticize: "duominike",
      commonName: "Dominica",
      disablePrefill: false,
      displayName: "多米尼克",
      enable: true,
      formalName: "Commonwealth of Dominica",
      id: "DM",
      localName: "",
      nationalFlag: "🇩🇲",
      startChar: "D",
      telephoneCode: "1767",
    },
  ],
  E: [
    {
      chineseName: "厄瓜多尔",
      chinesePhoneticize: "eguaduoer",
      commonName: "Ecuador",
      disablePrefill: false,
      displayName: "厄瓜多尔",
      enable: true,
      formalName: "Republic of Ecuador",
      id: "EC",
      localName: "",
      nationalFlag: "🇪🇨",
      startChar: "E",
      telephoneCode: "593",
    },
    {
      chineseName: "厄立特里亚",
      chinesePhoneticize: "eliteliya",
      commonName: "Eritrea",
      disablePrefill: false,
      displayName: "厄立特里亚",
      enable: true,
      formalName: "State of Eritrea",
      id: "ER",
      localName: "",
      nationalFlag: "🇪🇷",
      startChar: "E",
      telephoneCode: "291",
    },
    {
      chineseName: "俄国",
      chinesePhoneticize: "eluosi",
      commonName: "Russia",
      disablePrefill: false,
      displayName: "俄国",
      enable: true,
      formalName: "Russian Federation",
      id: "RU",
      localName: "",
      nationalFlag: "🇷🇺",
      startChar: "R",
      telephoneCode: "7",
    },
  ],
  F: [
    {
      chineseName: "法国",
      chinesePhoneticize: "faguo",
      commonName: "France",
      disablePrefill: false,
      displayName: "法国",
      enable: true,
      formalName: "French Republic",
      id: "FR",
      localName: "",
      nationalFlag: "🇫🇷",
      startChar: "F",
      telephoneCode: "33",
    },
    {
      chineseName: "法罗群岛",
      chinesePhoneticize: "faluoqundao",
      commonName: "Faroe Islands",
      disablePrefill: false,
      displayName: "法罗群岛",
      enable: true,
      formalName: "Faroe Islands (Autonomous Territory of Denmark)",
      id: "FO",
      localName: "",
      nationalFlag: "🇫🇴",
      startChar: "F",
      telephoneCode: "298",
    },
    {
      chineseName: "梵蒂冈城",
      chinesePhoneticize: "fandigangcheng",
      commonName: "Vatican City",
      disablePrefill: false,
      displayName: "梵蒂冈城",
      enable: true,
      formalName: "State of the Vatican City",
      id: "VA",
      localName: "",
      nationalFlag: "🇻🇦",
      startChar: "V",
      telephoneCode: "379",
    },
    {
      chineseName: "法属波利尼西亚",
      chinesePhoneticize: "fashubolinixiya",
      commonName: "French Polynesia",
      disablePrefill: false,
      displayName: "法属波利尼西亚",
      enable: true,
      formalName: "french polynesia",
      id: "PF",
      localName: "",
      nationalFlag: "🇵🇫",
      startChar: "F",
      telephoneCode: "689",
    },
    {
      chineseName: "斐济",
      chinesePhoneticize: "feiji",
      commonName: "Fiji",
      disablePrefill: false,
      displayName: "斐济",
      enable: true,
      formalName: "Republic of the Fiji Islands",
      id: "FJ",
      localName: "",
      nationalFlag: "🇫🇯",
      startChar: "F",
      telephoneCode: "679",
    },
    {
      chineseName: "菲律宾",
      chinesePhoneticize: "feilübin",
      commonName: "Philippines",
      disablePrefill: false,
      displayName: "菲律宾",
      enable: true,
      formalName: "Republic of the Philippines",
      id: "PH",
      localName: "",
      nationalFlag: "🇵🇭",
      startChar: "P",
      telephoneCode: "63",
    },
    {
      chineseName: "芬兰",
      chinesePhoneticize: "fenlan",
      commonName: "Finland",
      disablePrefill: false,
      displayName: "芬兰",
      enable: true,
      formalName: "Republic of Finland",
      id: "FI",
      localName: "",
      nationalFlag: "🇫🇮",
      startChar: "F",
      telephoneCode: "358",
    },
    {
      chineseName: "佛得角",
      chinesePhoneticize: "fodejiao",
      commonName: "Cape Verde",
      disablePrefill: false,
      displayName: "佛得角",
      enable: true,
      formalName: "Republic of Cape Verde",
      id: "CV",
      localName: "",
      nationalFlag: "🇨🇻",
      startChar: "C",
      telephoneCode: "238",
    },
  ],
  G: [
    {
      chineseName: "冈比亚",
      chinesePhoneticize: "gangbiya",
      commonName: "Gambia",
      disablePrefill: false,
      displayName: "冈比亚",
      enable: true,
      formalName: "Republic of The Gambia",
      id: "GM",
      localName: "",
      nationalFlag: "🇬🇲",
      startChar: "G",
      telephoneCode: "220",
    },
    {
      chineseName: "刚果共和国",
      chinesePhoneticize: "gangguogongheguo",
      commonName: "Congo (Republic)",
      disablePrefill: false,
      displayName: "刚果共和国",
      enable: true,
      formalName: "Republic of the Congo",
      id: "CG",
      localName: "",
      nationalFlag: "🇨🇬",
      startChar: "C",
      telephoneCode: "242",
    },
    {
      chineseName: "刚果民主共和国",
      chinesePhoneticize: "gangguominzhugongheguo",
      commonName: "Congo (Democratic Republic)",
      disablePrefill: false,
      displayName: "刚果民主共和国",
      enable: true,
      formalName: "Democratic&nbsp;Republic&nbsp;of&nbsp;the&nbsp;Congo",
      id: "CD",
      localName: "",
      nationalFlag: "🇨🇩",
      startChar: "C",
      telephoneCode: "243",
    },
    {
      chineseName: "格陵兰岛",
      chinesePhoneticize: "gelinglandao",
      commonName: "Greenland",
      disablePrefill: false,
      displayName: "格陵兰岛",
      enable: true,
      formalName: "Greenland (Autonomous Territory of Denmark)",
      id: "GL",
      localName: "",
      nationalFlag: "🇬🇱",
      startChar: "G",
      telephoneCode: "299",
    },
    {
      chineseName: "格林纳达",
      chinesePhoneticize: "gelinnada",
      commonName: "Grenada",
      disablePrefill: false,
      displayName: "格林纳达",
      enable: true,
      formalName: "",
      id: "GD",
      localName: "",
      nationalFlag: "🇬🇩",
      startChar: "G",
      telephoneCode: "1473",
    },
    {
      chineseName: "格鲁吉亚",
      chinesePhoneticize: "gelujiya",
      commonName: "Georgia",
      disablePrefill: false,
      displayName: "格鲁吉亚",
      enable: true,
      formalName: "Republic of Georgia",
      id: "GE",
      localName: "",
      nationalFlag: "🇬🇪",
      startChar: "G",
      telephoneCode: "995",
    },
    {
      chineseName: "哥伦比亚",
      chinesePhoneticize: "gelunbiya",
      commonName: "Colombia",
      disablePrefill: false,
      displayName: "哥伦比亚",
      enable: true,
      formalName: "Republic of Colombia",
      id: "CO",
      localName: "",
      nationalFlag: "🇨🇴",
      startChar: "C",
      telephoneCode: "57",
    },
    {
      chineseName: "根西岛",
      chinesePhoneticize: "genxidao",
      commonName: "Guernsey",
      disablePrefill: false,
      displayName: "根西岛",
      enable: true,
      formalName: "Bailiwick of Guernsey",
      id: "GG",
      localName: "",
      nationalFlag: "🇬🇬",
      startChar: "G",
      telephoneCode: "1481",
    },
    {
      chineseName: "哥斯达黎加",
      chinesePhoneticize: "gesidalijia",
      commonName: "Costa Rica",
      disablePrefill: false,
      displayName: "哥斯达黎加",
      enable: true,
      formalName: "Republic of Costa Rica",
      id: "CR",
      localName: "",
      nationalFlag: "🇨🇷",
      startChar: "C",
      telephoneCode: "506",
    },
    {
      chineseName: "瓜德罗普",
      chinesePhoneticize: "guadeluopu",
      commonName: "Guadeloupe",
      disablePrefill: false,
      displayName: "瓜德罗普",
      enable: true,
      formalName: "Guadeloupe",
      id: "GP",
      localName: "",
      nationalFlag: "🇬🇵",
      startChar: "G",
      telephoneCode: "590",
    },
    {
      chineseName: "关岛",
      chinesePhoneticize: "guandao",
      commonName: "Guam",
      disablePrefill: false,
      displayName: "关岛",
      enable: true,
      formalName: "Guam",
      id: "GU",
      localName: "",
      nationalFlag: "🇬🇺",
      startChar: "G",
      telephoneCode: "1",
    },
    {
      chineseName: "古巴",
      chinesePhoneticize: "guba",
      commonName: "Cuba",
      disablePrefill: false,
      displayName: "古巴",
      enable: false,
      formalName: "Republic of Cuba",
      id: "CU",
      localName: "",
      nationalFlag: "🇨🇺",
      startChar: "C",
      telephoneCode: "53",
    },
    {
      chineseName: "圭亚那",
      chinesePhoneticize: "guiyana",
      commonName: "Guyana",
      disablePrefill: false,
      displayName: "圭亚那",
      enable: true,
      formalName: "Co-operative&nbsp;Republic&nbsp;of&nbsp;Guyana",
      id: "GY",
      localName: "",
      nationalFlag: "🇬🇾",
      startChar: "G",
      telephoneCode: "592",
    },
  ],
  H: [
    {
      chineseName: "海地",
      chinesePhoneticize: "haidi",
      commonName: "Haiti",
      disablePrefill: false,
      displayName: "海地",
      enable: true,
      formalName: "Republic of Haiti",
      id: "HT",
      localName: "",
      nationalFlag: "🇭🇹",
      startChar: "H",
      telephoneCode: "509",
    },
    {
      chineseName: "韩国",
      chinesePhoneticize: "hanguo",
      commonName: "South Korea",
      disablePrefill: false,
      displayName: "韩国",
      enable: true,
      formalName: "Republic of Korea",
      id: "KR",
      localName: "",
      nationalFlag: "🇰🇷",
      startChar: "S",
      telephoneCode: "82",
    },
    {
      chineseName: "哈萨克斯坦",
      chinesePhoneticize: "hasakesitan",
      commonName: "Kazakhstan",
      disablePrefill: false,
      displayName: "哈萨克斯坦",
      enable: true,
      formalName: "Republic of Kazakhstan",
      id: "KZ",
      localName: "",
      nationalFlag: "🇰🇿",
      startChar: "K",
      telephoneCode: "7",
    },
    {
      chineseName: "黑山",
      chinesePhoneticize: "heishan",
      commonName: "Montenegro",
      disablePrefill: false,
      displayName: "黑山",
      enable: true,
      formalName: "Republic of Montenegro",
      id: "ME",
      localName: "",
      nationalFlag: "🇲🇪",
      startChar: "M",
      telephoneCode: "382",
    },
    {
      chineseName: "荷兰",
      chinesePhoneticize: "helan",
      commonName: "Netherlands",
      disablePrefill: false,
      displayName: "荷兰",
      enable: true,
      formalName: "Kingdom of the Netherlands",
      id: "NL",
      localName: "",
      nationalFlag: "🇳🇱",
      startChar: "N",
      telephoneCode: "31",
    },
    {
      chineseName: "荷属圣马丁",
      chinesePhoneticize: "heshushengmading",
      commonName: "Sint Maarten",
      disablePrefill: false,
      displayName: "荷属圣马丁",
      enable: true,
      formalName: "Sint Maarten",
      id: "SX",
      localName: "",
      nationalFlag: "🇸🇽",
      startChar: "S",
      telephoneCode: "721",
    },
    {
      chineseName: "洪都拉斯",
      chinesePhoneticize: "hongdulasi",
      commonName: "Honduras",
      disablePrefill: false,
      displayName: "洪都拉斯",
      enable: true,
      formalName: "Republic of Honduras",
      id: "HN",
      localName: "",
      nationalFlag: "🇭🇳",
      startChar: "H",
      telephoneCode: "504",
    },
  ],
  J: [
    {
      chineseName: "加纳",
      chinesePhoneticize: "jiana",
      commonName: "Ghana",
      disablePrefill: false,
      displayName: "加纳",
      enable: true,
      formalName: "Republic of Ghana",
      id: "GH",
      localName: "",
      nationalFlag: "🇬🇭",
      startChar: "G",
      telephoneCode: "233",
    },
    {
      chineseName: "加拿大",
      chinesePhoneticize: "jianada",
      commonName: "Canada",
      disablePrefill: false,
      displayName: "加拿大",
      enable: true,
      formalName: "",
      id: "CA",
      localName: "",
      nationalFlag: "🇨🇦",
      startChar: "C",
      telephoneCode: "1",
    },
    {
      chineseName: "柬埔寨",
      chinesePhoneticize: "jianpuzhai",
      commonName: "Cambodia",
      disablePrefill: false,
      displayName: "柬埔寨",
      enable: true,
      formalName: "Kingdom of Cambodia",
      id: "KH",
      localName: "",
      nationalFlag: "🇰🇭",
      startChar: "C",
      telephoneCode: "855",
    },
    {
      chineseName: "加蓬",
      chinesePhoneticize: "jiapeng",
      commonName: "Gabon",
      disablePrefill: false,
      displayName: "加蓬",
      enable: true,
      formalName: "Gabonese Republic",
      id: "GA",
      localName: "",
      nationalFlag: "🇬🇦",
      startChar: "G",
      telephoneCode: "241",
    },
    {
      chineseName: "吉布提",
      chinesePhoneticize: "jibuti",
      commonName: "Djibouti",
      disablePrefill: false,
      displayName: "吉布提",
      enable: true,
      formalName: "Republic of Djibouti",
      id: "DJ",
      localName: "",
      nationalFlag: "🇩🇯",
      startChar: "D",
      telephoneCode: "253",
    },
    {
      chineseName: "捷克共和国",
      chinesePhoneticize: "jiekegongheguo",
      commonName: "Czech Republic",
      disablePrefill: false,
      displayName: "捷克共和国",
      enable: true,
      formalName: "",
      id: "CZ",
      localName: "",
      nationalFlag: "🇨🇿",
      startChar: "C",
      telephoneCode: "420",
    },
    {
      chineseName: "吉尔吉斯斯坦",
      chinesePhoneticize: "jierjisisitan",
      commonName: "Kyrgyzstan",
      disablePrefill: false,
      displayName: "吉尔吉斯斯坦",
      enable: true,
      formalName: "Kyrgyz&nbsp;Republic",
      id: "KG",
      localName: "",
      nationalFlag: "🇰🇬",
      startChar: "K",
      telephoneCode: "996",
    },
    {
      chineseName: "基里巴斯",
      chinesePhoneticize: "jilibasi",
      commonName: "Kiribati",
      disablePrefill: false,
      displayName: "基里巴斯",
      enable: true,
      formalName: "Republic of Kiribati",
      id: "KI",
      localName: "",
      nationalFlag: "🇰🇮",
      startChar: "K",
      telephoneCode: "686",
    },
    {
      chineseName: "津巴布韦",
      chinesePhoneticize: "jinbabuwei",
      commonName: "Zimbabwe",
      disablePrefill: false,
      displayName: "津巴布韦",
      enable: true,
      formalName: "Republic&nbsp;of&nbsp;Zimbabwe",
      id: "ZW",
      localName: "",
      nationalFlag: "🇿🇼",
      startChar: "Z",
      telephoneCode: "263",
    },
    {
      chineseName: "几内亚",
      chinesePhoneticize: "jineiya",
      commonName: "Guinea",
      disablePrefill: false,
      displayName: "几内亚",
      enable: true,
      formalName: "Republic of Guinea",
      id: "GN",
      localName: "",
      nationalFlag: "🇬🇳",
      startChar: "G",
      telephoneCode: "224",
    },
    {
      chineseName: "几内亚比绍",
      chinesePhoneticize: "jineiyabishao",
      commonName: "Guinea-Bissau",
      disablePrefill: false,
      displayName: "几内亚比绍",
      enable: true,
      formalName: "Republic of Guinea-Bissau",
      id: "GW",
      localName: "",
      nationalFlag: "🇬🇼",
      startChar: "G",
      telephoneCode: "245",
    },
  ],
  K: [
    {
      chineseName: "开曼群岛",
      chinesePhoneticize: "kaimanqundao",
      commonName: "Cayman Islands",
      disablePrefill: false,
      displayName: "开曼群岛",
      enable: true,
      formalName: "",
      id: "KY",
      localName: "",
      nationalFlag: "🇰🇾",
      startChar: "C",
      telephoneCode: "1345",
    },
    {
      chineseName: "喀麦隆",
      chinesePhoneticize: "kamailong",
      commonName: "Cameroon",
      disablePrefill: false,
      displayName: "喀麦隆",
      enable: true,
      formalName: "Republic of Cameroon",
      id: "CM",
      localName: "",
      nationalFlag: "🇨🇲",
      startChar: "C",
      telephoneCode: "237",
    },
    {
      chineseName: "卡塔尔",
      chinesePhoneticize: "kataer",
      commonName: "Qatar",
      disablePrefill: false,
      displayName: "卡塔尔",
      enable: true,
      formalName: "State of Qatar",
      id: "QA",
      localName: "",
      nationalFlag: "🇶🇦",
      startChar: "Q",
      telephoneCode: "974",
    },
    {
      chineseName: "克罗地亚",
      chinesePhoneticize: "keluodiya",
      commonName: "Croatia",
      disablePrefill: false,
      displayName: "克罗地亚",
      enable: true,
      formalName: "Republic of Croatia",
      id: "HR",
      localName: "",
      nationalFlag: "🇭🇷",
      startChar: "C",
      telephoneCode: "385",
    },
    {
      chineseName: "科摩罗",
      chinesePhoneticize: "kemoluo",
      commonName: "Comoros",
      disablePrefill: false,
      displayName: "科摩罗",
      enable: true,
      formalName: "Union of Comoros",
      id: "KM",
      localName: "",
      nationalFlag: "🇰🇲",
      startChar: "C",
      telephoneCode: "269",
    },
    {
      chineseName: "肯尼亚",
      chinesePhoneticize: "kenniya",
      commonName: "Kenya",
      disablePrefill: false,
      displayName: "肯尼亚",
      enable: true,
      formalName: "Republic of Kenya",
      id: "KE",
      localName: "",
      nationalFlag: "🇰🇪",
      startChar: "K",
      telephoneCode: "254",
    },
    {
      chineseName: "科索沃",
      chinesePhoneticize: "kesuowo",
      commonName: "Kosovo",
      disablePrefill: false,
      displayName: "科索沃",
      enable: true,
      formalName: "Republic of Kosovo",
      id: "XK",
      localName: "",
      nationalFlag: "",
      startChar: "K",
      telephoneCode: "383",
    },
    {
      chineseName: "科威特",
      chinesePhoneticize: "keweite",
      commonName: "Kuwait",
      disablePrefill: false,
      displayName: "科威特",
      enable: true,
      formalName: "State of Kuwait",
      id: "KW",
      localName: "",
      nationalFlag: "🇰🇼",
      startChar: "K",
      telephoneCode: "965",
    },
    {
      chineseName: "库克群岛",
      chinesePhoneticize: "kukequndao",
      commonName: "Cook Islands",
      disablePrefill: false,
      displayName: "库克群岛",
      enable: true,
      formalName: "The Cook Islands",
      id: "CK",
      localName: "",
      nationalFlag: "🇨🇰",
      startChar: "C",
      telephoneCode: "682",
    },
    {
      chineseName: "库拉索",
      chinesePhoneticize: "kulasuo",
      commonName: "Curacao",
      disablePrefill: false,
      displayName: "库拉索",
      enable: true,
      formalName: "Curacao",
      id: "CW",
      localName: "",
      nationalFlag: "🇨🇼",
      startChar: "C",
      telephoneCode: "599",
    },
  ],
  L: [
    {
      chineseName: "莱索托",
      chinesePhoneticize: "laisuotuo",
      commonName: "Lesotho",
      disablePrefill: false,
      displayName: "莱索托",
      enable: true,
      formalName: "Kingdom of Lesotho",
      id: "LS",
      localName: "",
      nationalFlag: "🇱🇸",
      startChar: "L",
      telephoneCode: "266",
    },
    {
      chineseName: "老挝",
      chinesePhoneticize: "laowo",
      commonName: "Laos",
      disablePrefill: false,
      displayName: "老挝",
      enable: true,
      formalName: "Lao&nbsp;People&acute;s&nbsp;Democratic&nbsp;Republic",
      id: "LA",
      localName: "",
      nationalFlag: "🇱🇦",
      startChar: "L",
      telephoneCode: "856",
    },
    {
      chineseName: "拉脱维亚",
      chinesePhoneticize: "latuoweiya",
      commonName: "Latvia",
      disablePrefill: false,
      displayName: "拉脱维亚",
      enable: true,
      formalName: "Republic of Latvia",
      id: "LV",
      localName: "",
      nationalFlag: "🇱🇻",
      startChar: "L",
      telephoneCode: "371",
    },
    {
      chineseName: "黎巴嫩",
      chinesePhoneticize: "libanen",
      commonName: "Lebanon",
      disablePrefill: false,
      displayName: "黎巴嫩",
      enable: true,
      formalName: "Lebanese&nbsp;Republic",
      id: "LB",
      localName: "",
      nationalFlag: "🇱🇧",
      startChar: "L",
      telephoneCode: "961",
    },
    {
      chineseName: "利比里亚",
      chinesePhoneticize: "libiliya",
      commonName: "Liberia",
      disablePrefill: false,
      displayName: "利比里亚",
      enable: true,
      formalName: "Republic of Liberia",
      id: "LR",
      localName: "",
      nationalFlag: "🇱🇷",
      startChar: "L",
      telephoneCode: "231",
    },
    {
      chineseName: "利比亚",
      chinesePhoneticize: "libiya",
      commonName: "Libya",
      disablePrefill: false,
      displayName: "利比亚",
      enable: true,
      formalName:
        "Great&nbsp;Socialist&nbsp;People&acute;s&nbsp;Libyan&nbsp;Arab&nbsp;Jamahiriya",
      id: "LY",
      localName: "",
      nationalFlag: "🇱🇾",
      startChar: "L",
      telephoneCode: "218",
    },
    {
      chineseName: "列支敦士登",
      chinesePhoneticize: "liezhidunshideng",
      commonName: "Liechtenstein",
      disablePrefill: false,
      displayName: "列支敦士登",
      enable: true,
      formalName: "Principality of Liechtenstein",
      id: "LI",
      localName: "",
      nationalFlag: "🇱🇮",
      startChar: "L",
      telephoneCode: "423",
    },
    {
      chineseName: "立陶宛",
      chinesePhoneticize: "litaowan",
      commonName: "Lithuania",
      disablePrefill: false,
      displayName: "立陶宛",
      enable: true,
      formalName: "Republic of Lithuania",
      id: "LT",
      localName: "",
      nationalFlag: "🇱🇹",
      startChar: "L",
      telephoneCode: "370",
    },
    {
      chineseName: "留尼旺",
      chinesePhoneticize: "liuniwang",
      commonName: "Reunion",
      disablePrefill: false,
      displayName: "留尼旺",
      enable: true,
      formalName: "Reunion Island",
      id: "RE",
      localName: "",
      nationalFlag: "🇷🇪",
      startChar: "R",
      telephoneCode: "262",
    },
    {
      chineseName: "罗马尼亚",
      chinesePhoneticize: "luomaniya",
      commonName: "Romania",
      disablePrefill: false,
      displayName: "罗马尼亚",
      enable: true,
      formalName: "",
      id: "RO",
      localName: "",
      nationalFlag: "🇷🇴",
      startChar: "R",
      telephoneCode: "40",
    },
    {
      chineseName: "卢森堡",
      chinesePhoneticize: "lusenbao",
      commonName: "Luxembourg",
      disablePrefill: false,
      displayName: "卢森堡",
      enable: true,
      formalName: "Grand Duchy of Luxembourg",
      id: "LU",
      localName: "",
      nationalFlag: "🇱🇺",
      startChar: "L",
      telephoneCode: "352",
    },
    {
      chineseName: "卢旺达",
      chinesePhoneticize: "luwangda",
      commonName: "Rwanda",
      disablePrefill: false,
      displayName: "卢旺达",
      enable: true,
      formalName: "Republic of Rwanda",
      id: "RW",
      localName: "",
      nationalFlag: "🇷🇼",
      startChar: "R",
      telephoneCode: "250",
    },
  ],
  M: [
    {
      chineseName: "马达加斯加",
      chinesePhoneticize: "madajiasijia",
      commonName: "Madagascar",
      disablePrefill: false,
      displayName: "马达加斯加",
      enable: true,
      formalName: "Republic of Madagascar",
      id: "MG",
      localName: "",
      nationalFlag: "🇲🇬",
      startChar: "M",
      telephoneCode: "261",
    },
    {
      chineseName: "马尔代夫",
      chinesePhoneticize: "maerdaifu",
      commonName: "Maldives",
      disablePrefill: false,
      displayName: "马尔代夫",
      enable: true,
      formalName: "Republic of Maldives",
      id: "MV",
      localName: "",
      nationalFlag: "🇲🇻",
      startChar: "M",
      telephoneCode: "960",
    },
    {
      chineseName: "马耳他",
      chinesePhoneticize: "maerta",
      commonName: "Malta",
      disablePrefill: false,
      displayName: "马耳他",
      enable: true,
      formalName: "Republic of Malta",
      id: "MT",
      localName: "",
      nationalFlag: "🇲🇹",
      startChar: "M",
      telephoneCode: "356",
    },
    {
      chineseName: "马来西亚",
      chinesePhoneticize: "malaixiya",
      commonName: "Malaysia",
      disablePrefill: false,
      displayName: "马来西亚",
      enable: true,
      formalName: "",
      id: "MY",
      localName: "",
      nationalFlag: "🇲🇾",
      startChar: "M",
      telephoneCode: "60",
    },
    {
      chineseName: "马拉维",
      chinesePhoneticize: "malawei",
      commonName: "Malawi",
      disablePrefill: false,
      displayName: "马拉维",
      enable: true,
      formalName: "Republic of Malawi",
      id: "MW",
      localName: "",
      nationalFlag: "🇲🇼",
      startChar: "M",
      telephoneCode: "265",
    },
    {
      chineseName: "马里",
      chinesePhoneticize: "mali",
      commonName: "Mali",
      disablePrefill: false,
      displayName: "马里",
      enable: true,
      formalName: "Republic of Mali",
      id: "ML",
      localName: "",
      nationalFlag: "🇲🇱",
      startChar: "M",
      telephoneCode: "223",
    },
    {
      chineseName: "曼岛",
      chinesePhoneticize: "mandao",
      commonName: "Isle of Man",
      disablePrefill: false,
      displayName: "马恩岛",
      enable: true,
      formalName: "Isle of Man",
      id: "IM",
      localName: "",
      nationalFlag: "🇮🇲",
      startChar: "I",
      telephoneCode: "44",
    },
    {
      chineseName: "毛里求斯",
      chinesePhoneticize: "maoliqiusi",
      commonName: "Mauritius",
      disablePrefill: false,
      displayName: "毛里求斯",
      enable: true,
      formalName: "Republic of Mauritius",
      id: "MU",
      localName: "",
      nationalFlag: "🇲🇺",
      startChar: "M",
      telephoneCode: "230",
    },
    {
      chineseName: "毛里塔尼亚",
      chinesePhoneticize: "maolitaniya",
      commonName: "Mauritania",
      disablePrefill: false,
      displayName: "毛里塔尼亚",
      enable: true,
      formalName: "Islamic Republic of Mauritania",
      id: "MR",
      localName: "",
      nationalFlag: "🇲🇷",
      startChar: "M",
      telephoneCode: "222",
    },
    {
      chineseName: "马其顿",
      chinesePhoneticize: "maqidun",
      commonName: "Macedonia",
      disablePrefill: false,
      displayName: "马其顿",
      enable: true,
      formalName: "Republic of Macedonia",
      id: "MK",
      localName: "",
      nationalFlag: "🇲🇰",
      startChar: "M",
      telephoneCode: "389",
    },
    {
      chineseName: "马绍尔群岛",
      chinesePhoneticize: "mashaoerqundao",
      commonName: "Marshall Islands",
      disablePrefill: false,
      displayName: "马绍尔群岛",
      enable: true,
      formalName: "Republic of the Marshall Islands",
      id: "MH",
      localName: "",
      nationalFlag: "🇲🇭",
      startChar: "M",
      telephoneCode: "692",
    },
    {
      chineseName: "马提尼克",
      chinesePhoneticize: "matinike",
      commonName: "Martinique",
      disablePrefill: false,
      displayName: "马提尼克",
      enable: true,
      formalName: "Martinique",
      id: "MQ",
      localName: "",
      nationalFlag: "🇲🇶",
      startChar: "M",
      telephoneCode: "596",
    },
    {
      chineseName: "美国",
      chinesePhoneticize: "meiguo",
      commonName: "United States",
      disablePrefill: false,
      displayName: "美国",
      enable: true,
      formalName: "United&nbsp;States&nbsp;of&nbsp;America",
      id: "US",
      localName: "",
      nationalFlag: "🇺🇸",
      startChar: "U",
      telephoneCode: "1",
    },
    {
      chineseName: "美属维尔京群岛",
      chinesePhoneticize: "meishuweierjingqundao",
      commonName: "U.S. Virgin Islands",
      disablePrefill: false,
      displayName: "美属维尔京群岛",
      enable: true,
      formalName: "United&nbsp;States&nbsp;Virgin&nbsp;Islands",
      id: "VI",
      localName: "",
      nationalFlag: "🇻🇮",
      startChar: "U",
      telephoneCode: "1340",
    },
    {
      chineseName: "蒙古",
      chinesePhoneticize: "menggu",
      commonName: "Mongolia",
      disablePrefill: false,
      displayName: "蒙古",
      enable: true,
      formalName: "",
      id: "MN",
      localName: "",
      nationalFlag: "🇲🇳",
      startChar: "M",
      telephoneCode: "976",
    },
    {
      chineseName: "孟加拉国",
      chinesePhoneticize: "mengjialaguo",
      commonName: "Bangladesh",
      disablePrefill: false,
      displayName: "孟加拉国",
      enable: true,
      formalName: "People&acute;s&nbsp;Republic&nbsp;of&nbsp;Bangladesh",
      id: "BD",
      localName: "",
      nationalFlag: "🇧🇩",
      startChar: "B",
      telephoneCode: "880",
    },
    {
      chineseName: "缅甸",
      chinesePhoneticize: "miandian",
      commonName: "Myanmar (Burma)",
      disablePrefill: false,
      displayName: "缅甸",
      enable: true,
      formalName: "Union&nbsp;of&nbsp;Myanmar",
      id: "MM",
      localName: "",
      nationalFlag: "🇲🇲",
      startChar: "M",
      telephoneCode: "95",
    },
    {
      chineseName: "密克罗尼西亚",
      chinesePhoneticize: "mikeluonixiya",
      commonName: "Micronesia",
      disablePrefill: false,
      displayName: "密克罗尼西亚",
      enable: true,
      formalName: "Federated States of Micronesia",
      id: "FM",
      localName: "",
      nationalFlag: "🇫🇲",
      startChar: "M",
      telephoneCode: "691",
    },
    {
      chineseName: "秘鲁",
      chinesePhoneticize: "milu",
      commonName: "Peru",
      disablePrefill: false,
      displayName: "秘鲁",
      enable: true,
      formalName: "Republic of Peru",
      id: "PE",
      localName: "",
      nationalFlag: "🇵🇪",
      startChar: "P",
      telephoneCode: "51",
    },
    {
      chineseName: "摩尔多瓦",
      chinesePhoneticize: "moerduowa",
      commonName: "Moldova",
      disablePrefill: false,
      displayName: "摩尔多瓦",
      enable: true,
      formalName: "Republic of Moldova",
      id: "MD",
      localName: "",
      nationalFlag: "🇲🇩",
      startChar: "M",
      telephoneCode: "373",
    },
    {
      chineseName: "摩洛哥",
      chinesePhoneticize: "moluoge",
      commonName: "Morocco",
      disablePrefill: false,
      displayName: "摩洛哥",
      enable: true,
      formalName: "Kingdom of Morocco",
      id: "MA",
      localName: "",
      nationalFlag: "🇲🇦",
      startChar: "M",
      telephoneCode: "212",
    },
    {
      chineseName: "摩纳哥",
      chinesePhoneticize: "monage",
      commonName: "Monaco",
      disablePrefill: false,
      displayName: "摩纳哥",
      enable: true,
      formalName: "Principality of Monaco",
      id: "MC",
      localName: "",
      nationalFlag: "🇲🇨",
      startChar: "M",
      telephoneCode: "377",
    },
    {
      chineseName: "莫桑比克",
      chinesePhoneticize: "mosangbike",
      commonName: "Mozambique",
      disablePrefill: false,
      displayName: "莫桑比克",
      enable: true,
      formalName: "Republic of Mozambique",
      id: "MZ",
      localName: "",
      nationalFlag: "🇲🇿",
      startChar: "M",
      telephoneCode: "258",
    },
    {
      chineseName: "墨西哥",
      chinesePhoneticize: "moxige",
      commonName: "Mexico",
      disablePrefill: false,
      displayName: "墨西哥",
      enable: true,
      formalName: "United Mexican States",
      id: "MX",
      localName: "",
      nationalFlag: "🇲🇽",
      startChar: "M",
      telephoneCode: "52",
    },
  ],
  N: [
    {
      chineseName: "纳米比亚",
      chinesePhoneticize: "namibiya",
      commonName: "Namibia",
      disablePrefill: false,
      displayName: "纳米比亚",
      enable: true,
      formalName: "Republic of Namibia",
      id: "NA",
      localName: "",
      nationalFlag: "🇳🇦",
      startChar: "N",
      telephoneCode: "264",
    },
    {
      chineseName: "南非",
      chinesePhoneticize: "nanfei",
      commonName: "South Africa",
      disablePrefill: false,
      displayName: "南非",
      enable: true,
      formalName: "Republic of South Africa",
      id: "ZA",
      localName: "",
      nationalFlag: "🇿🇦",
      startChar: "S",
      telephoneCode: "27",
    },
    {
      chineseName: "南苏丹",
      chinesePhoneticize: "nansudan",
      commonName: "South Sudan",
      disablePrefill: false,
      displayName: "南苏丹",
      enable: true,
      formalName: "Republic of South Sudan",
      id: "SS",
      localName: "",
      nationalFlag: "🇸🇸",
      startChar: "S",
      telephoneCode: "211",
    },
    {
      chineseName: "瑙鲁",
      chinesePhoneticize: "naolu",
      commonName: "Nauru",
      disablePrefill: false,
      displayName: "瑙鲁",
      enable: true,
      formalName: "Republic of Nauru",
      id: "NR",
      localName: "",
      nationalFlag: "🇳🇷",
      startChar: "N",
      telephoneCode: "674",
    },
    {
      chineseName: "尼泊尔",
      chinesePhoneticize: "niboer",
      commonName: "Nepal",
      disablePrefill: false,
      displayName: "尼泊尔",
      enable: true,
      formalName: "",
      id: "NP",
      localName: "",
      nationalFlag: "🇳🇵",
      startChar: "N",
      telephoneCode: "977",
    },
    {
      chineseName: "尼加拉瓜",
      chinesePhoneticize: "nijialagua",
      commonName: "Nicaragua",
      disablePrefill: false,
      displayName: "尼加拉瓜",
      enable: true,
      formalName: "Republic of Nicaragua",
      id: "NI",
      localName: "",
      nationalFlag: "🇳🇮",
      startChar: "N",
      telephoneCode: "505",
    },
    {
      chineseName: "尼日尔",
      chinesePhoneticize: "nirier",
      commonName: "Niger",
      disablePrefill: false,
      displayName: "尼日尔",
      enable: true,
      formalName: "Republic of Niger",
      id: "NE",
      localName: "",
      nationalFlag: "🇳🇪",
      startChar: "N",
      telephoneCode: "227",
    },
    {
      chineseName: "尼日利亚",
      chinesePhoneticize: "niriliya",
      commonName: "Nigeria",
      disablePrefill: false,
      displayName: "尼日利亚",
      enable: true,
      formalName: "Federal Republic of Nigeria",
      id: "NG",
      localName: "",
      nationalFlag: "🇳🇬",
      startChar: "N",
      telephoneCode: "234",
    },
    {
      chineseName: "挪威",
      chinesePhoneticize: "nuowei",
      commonName: "Norway",
      disablePrefill: false,
      displayName: "挪威",
      enable: true,
      formalName: "Kingdom of Norway",
      id: "NO",
      localName: "",
      nationalFlag: "🇳🇴",
      startChar: "N",
      telephoneCode: "47",
    },
  ],
  P: [
    {
      chineseName: "帕劳",
      chinesePhoneticize: "palao",
      commonName: "Palau",
      disablePrefill: false,
      displayName: "帕劳",
      enable: true,
      formalName: "Republic of Palau",
      id: "PW",
      localName: "",
      nationalFlag: "🇵🇼",
      startChar: "P",
      telephoneCode: "680",
    },
    {
      chineseName: "葡萄牙",
      chinesePhoneticize: "putaoya",
      commonName: "Portugal",
      disablePrefill: false,
      displayName: "葡萄牙",
      enable: true,
      formalName: "Portuguese Republic",
      id: "PT",
      localName: "",
      nationalFlag: "🇵🇹",
      startChar: "P",
      telephoneCode: "351",
    },
  ],
  R: [
    {
      chineseName: "日本",
      chinesePhoneticize: "riben",
      commonName: "Japan",
      disablePrefill: false,
      displayName: "日本",
      enable: true,
      formalName: "",
      id: "JP",
      localName: "",
      nationalFlag: "🇯🇵",
      startChar: "J",
      telephoneCode: "81",
    },
    {
      chineseName: "瑞典",
      chinesePhoneticize: "ruidian",
      commonName: "Sweden",
      disablePrefill: false,
      displayName: "瑞典",
      enable: true,
      formalName: "Kingdom of Sweden",
      id: "SE",
      localName: "",
      nationalFlag: "🇸🇪",
      startChar: "S",
      telephoneCode: "46",
    },
    {
      chineseName: "瑞士",
      chinesePhoneticize: "ruishi",
      commonName: "Switzerland",
      disablePrefill: false,
      displayName: "瑞士",
      enable: true,
      formalName: "Swiss Confederation",
      id: "CH",
      localName: "",
      nationalFlag: "🇨🇭",
      startChar: "S",
      telephoneCode: "41",
    },
  ],
  // commonCountries: [
  //   {
  //     chineseName: "",
  //     chinesePhoneticize: "",
  //     commonName: "中国",
  //     disablePrefill: false,
  //     displayName: "中国",
  //     enable: true,
  //     formalName: "",
  //     id: "CN",
  //     localName: "",
  //     nationalFlag: "🇨🇳",
  //     startChar: "中",
  //     telephoneCode: "86",
  //   },
  //   {
  //     chineseName: "",
  //     chinesePhoneticize: "",
  //     commonName: "印度",
  //     disablePrefill: false,
  //     displayName: "印度",
  //     enable: true,
  //     formalName: "",
  //     id: "IN",
  //     localName: "",
  //     nationalFlag: "🇮🇳",
  //     startChar: "印",
  //     telephoneCode: "91",
  //   },
  //   {
  //     chineseName: "",
  //     chinesePhoneticize: "",
  //     commonName: "俄国",
  //     disablePrefill: false,
  //     displayName: "俄国",
  //     enable: true,
  //     formalName: "",
  //     id: "RU",
  //     localName: "",
  //     nationalFlag: "🇷🇺",
  //     startChar: "俄",
  //     telephoneCode: "7",
  //   },
  //   {
  //     chineseName: "",
  //     chinesePhoneticize: "",
  //     commonName: "土耳其",
  //     disablePrefill: false,
  //     displayName: "土耳其",
  //     enable: true,
  //     formalName: "",
  //     id: "TR",
  //     localName: "",
  //     nationalFlag: "🇹🇷",
  //     startChar: "土",
  //     telephoneCode: "90",
  //   },
  //   {
  //     chineseName: "",
  //     chinesePhoneticize: "",
  //     commonName: "日本",
  //     disablePrefill: false,
  //     displayName: "日本",
  //     enable: true,
  //     formalName: "",
  //     id: "JP",
  //     localName: "",
  //     nationalFlag: "🇯🇵",
  //     startChar: "日",
  //     telephoneCode: "81",
  //   },
  //   {
  //     chineseName: "",
  //     chinesePhoneticize: "",
  //     commonName: "泰国",
  //     disablePrefill: false,
  //     displayName: "泰国",
  //     enable: true,
  //     formalName: "",
  //     id: "TH",
  //     localName: "",
  //     nationalFlag: "🇹🇭",
  //     startChar: "泰",
  //     telephoneCode: "66",
  //   },
  //   {
  //     chineseName: "",
  //     chinesePhoneticize: "",
  //     commonName: "巴基斯坦",
  //     disablePrefill: false,
  //     displayName: "巴基斯坦",
  //     enable: true,
  //     formalName: "",
  //     id: "PK",
  //     localName: "",
  //     nationalFlag: "🇵🇰",
  //     startChar: "巴",
  //     telephoneCode: "92",
  //   },
  // ],
  // default: [
  //   {
  //     chineseName: "",
  //     chinesePhoneticize: "",
  //     commonName: "China",
  //     disablePrefill: false,
  //     displayName: "中国",
  //     enable: true,
  //     formalName: "",
  //     id: "CN",
  //     localName: "",
  //     nationalFlag: "🇨🇳",
  //     startChar: "C",
  //     telephoneCode: "86",
  //   },
  // ],
  S: [
    {
      chineseName: "萨尔瓦多",
      chinesePhoneticize: "saerwaduo",
      commonName: "El Salvador",
      disablePrefill: false,
      displayName: "萨尔瓦多",
      enable: true,
      formalName: "Republic of El Salvador",
      id: "SV",
      localName: "",
      nationalFlag: "🇸🇻",
      startChar: "E",
      telephoneCode: "503",
    },
    {
      chineseName: "塞尔维亚",
      chinesePhoneticize: "saierweiya",
      commonName: "Serbia",
      disablePrefill: false,
      displayName: "塞尔维亚",
      enable: true,
      formalName: "Republic of Serbia",
      id: "RS",
      localName: "",
      nationalFlag: "🇷🇸",
      startChar: "S",
      telephoneCode: "381",
    },
    {
      chineseName: "塞拉利昂",
      chinesePhoneticize: "sailaliang",
      commonName: "Sierra Leone",
      disablePrefill: false,
      displayName: "塞拉利昂",
      enable: true,
      formalName: "Republic of Sierra Leone",
      id: "SL",
      localName: "",
      nationalFlag: "🇸🇱",
      startChar: "S",
      telephoneCode: "232",
    },
    {
      chineseName: "塞内加尔",
      chinesePhoneticize: "saineijiaer",
      commonName: "Senegal",
      disablePrefill: false,
      displayName: "塞内加尔",
      enable: true,
      formalName: "Republic of Senegal",
      id: "SN",
      localName: "",
      nationalFlag: "🇸🇳",
      startChar: "S",
      telephoneCode: "221",
    },
    {
      chineseName: "塞浦路斯",
      chinesePhoneticize: "saipulusi",
      commonName: "Cyprus",
      disablePrefill: false,
      displayName: "塞浦路斯",
      enable: true,
      formalName: "Republic of Cyprus",
      id: "CY",
      localName: "",
      nationalFlag: "🇨🇾",
      startChar: "C",
      telephoneCode: "357",
    },
    {
      chineseName: "塞舌尔",
      chinesePhoneticize: "saisheer",
      commonName: "Seychelles",
      disablePrefill: false,
      displayName: "塞舌尔",
      enable: true,
      formalName: "Republic of Seychelles",
      id: "SC",
      localName: "",
      nationalFlag: "🇸🇨",
      startChar: "S",
      telephoneCode: "248",
    },
    {
      chineseName: "萨摩亚",
      chinesePhoneticize: "samoya",
      commonName: "Samoa",
      disablePrefill: false,
      displayName: "萨摩亚",
      enable: true,
      formalName: "Independent State of Samoa",
      id: "WS",
      localName: "",
      nationalFlag: "🇼🇸",
      startChar: "S",
      telephoneCode: "685",
    },
    {
      chineseName: "沙特阿拉伯",
      chinesePhoneticize: "shatealabo",
      commonName: "Saudi Arabia",
      disablePrefill: false,
      displayName: "沙特阿拉伯",
      enable: true,
      formalName: "Kingdom of Saudi Arabia",
      id: "SA",
      localName: "",
      nationalFlag: "🇸🇦",
      startChar: "S",
      telephoneCode: "966",
    },
    {
      chineseName: "圣多美和普林西比",
      chinesePhoneticize: "shengduomeihepulinxibi",
      commonName: "Sao Tome and Principe",
      disablePrefill: false,
      displayName: "圣多美和普林西比",
      enable: true,
      formalName: "Democratic Republic of Sao Tome and Principe",
      id: "ST",
      localName: "",
      nationalFlag: "🇸🇹",
      startChar: "S",
      telephoneCode: "239",
    },
    {
      chineseName: "圣基茨和尼维斯",
      chinesePhoneticize: "shengjiciheniweisi",
      commonName: "Saint Kitts and Nevis",
      disablePrefill: false,
      displayName: "圣基茨和尼维斯",
      enable: true,
      formalName: "Federation of Saint Kitts and Nevis",
      id: "KN",
      localName: "",
      nationalFlag: "🇰🇳",
      startChar: "S",
      telephoneCode: "1869",
    },
    {
      chineseName: "圣卢西亚",
      chinesePhoneticize: "shengluxiya",
      commonName: "Saint Lucia",
      disablePrefill: false,
      displayName: "圣卢西亚",
      enable: true,
      formalName: "",
      id: "LC",
      localName: "",
      nationalFlag: "🇱🇨",
      startChar: "S",
      telephoneCode: "1758",
    },
    {
      chineseName: "圣马力诺",
      chinesePhoneticize: "shengmalinuo",
      commonName: "San Marino",
      disablePrefill: false,
      displayName: "圣马力诺",
      enable: true,
      formalName: "Republic of San Marino",
      id: "SM",
      localName: "",
      nationalFlag: "🇸🇲",
      startChar: "S",
      telephoneCode: "378",
    },
    {
      chineseName: "圣文森特和格林纳丁斯",
      chinesePhoneticize: "shengwensentehegelinnadingsi",
      commonName: "Saint Vincent and the Grenadines",
      disablePrefill: false,
      displayName: "圣文森特和格林纳丁斯",
      enable: true,
      formalName: "",
      id: "VC",
      localName: "",
      nationalFlag: "🇻🇨",
      startChar: "S",
      telephoneCode: "1784",
    },
    {
      chineseName: "斯里兰卡",
      chinesePhoneticize: "sililanka",
      commonName: "Sri Lanka",
      disablePrefill: false,
      displayName: "斯里兰卡",
      enable: true,
      formalName: "Democratic Socialist Republic of Sri Lanka",
      id: "LK",
      localName: "",
      nationalFlag: "🇱🇰",
      startChar: "S",
      telephoneCode: "94",
    },
    {
      chineseName: "斯洛伐克",
      chinesePhoneticize: "siluofake",
      commonName: "Slovakia",
      disablePrefill: false,
      displayName: "斯洛伐克",
      enable: true,
      formalName: "Slovak Republic",
      id: "SK",
      localName: "",
      nationalFlag: "🇸🇰",
      startChar: "S",
      telephoneCode: "421",
    },
    {
      chineseName: "斯洛文尼亚",
      chinesePhoneticize: "siluowenniya",
      commonName: "Slovenia",
      disablePrefill: false,
      displayName: "斯洛文尼亚",
      enable: true,
      formalName: "Republic of Slovenia",
      id: "SI",
      localName: "",
      nationalFlag: "🇸🇮",
      startChar: "S",
      telephoneCode: "386",
    },
    {
      chineseName: "斯威士兰",
      chinesePhoneticize: "siweishilan",
      commonName: "Swaziland",
      disablePrefill: false,
      displayName: "斯威士兰",
      enable: true,
      formalName: "Kingdom of Swaziland",
      id: "SZ",
      localName: "",
      nationalFlag: "🇸🇿",
      startChar: "S",
      telephoneCode: "268",
    },
    {
      chineseName: "苏丹",
      chinesePhoneticize: "sudan",
      commonName: "Sudan",
      disablePrefill: false,
      displayName: "苏丹",
      enable: true,
      formalName: "Republic of the Sudan",
      id: "SD",
      localName: "",
      nationalFlag: "🇸🇩",
      startChar: "S",
      telephoneCode: "249",
    },
    {
      chineseName: "苏里南",
      chinesePhoneticize: "sulinan",
      commonName: "Suriname",
      disablePrefill: false,
      displayName: "苏里南",
      enable: true,
      formalName: "Republic of Suriname",
      id: "SR",
      localName: "",
      nationalFlag: "🇸🇷",
      startChar: "S",
      telephoneCode: "597",
    },
    {
      chineseName: "所罗门群岛",
      chinesePhoneticize: "suoluomenqundao",
      commonName: "Solomon Islands",
      disablePrefill: false,
      displayName: "所罗门群岛",
      enable: true,
      formalName: "",
      id: "SB",
      localName: "",
      nationalFlag: "🇸🇧",
      startChar: "S",
      telephoneCode: "677",
    },
    {
      chineseName: "索马里",
      chinesePhoneticize: "suomali",
      commonName: "Somalia",
      disablePrefill: false,
      displayName: "索马里",
      enable: true,
      formalName: "null",
      id: "SO",
      localName: "",
      nationalFlag: "🇸🇴",
      startChar: "S",
      telephoneCode: "252",
    },
  ],
  T: [
    {
      chineseName: "泰国",
      chinesePhoneticize: "taiguo",
      commonName: "Thailand",
      disablePrefill: false,
      displayName: "泰国",
      enable: true,
      formalName: "Kingdom of Thailand",
      id: "TH",
      localName: "",
      nationalFlag: "🇹🇭",
      startChar: "T",
      telephoneCode: "66",
    },
    {
      chineseName: "台湾",
      chinesePhoneticize: "taiwan",
      commonName: "Taiwan",
      disablePrefill: false,
      displayName: "中国台湾",
      enable: true,
      formalName: "Republic&nbsp;of&nbsp;China",
      id: "TW",
      localName: "",
      nationalFlag: "",
      startChar: "T",
      telephoneCode: "886",
    },
    {
      chineseName: "塔吉克斯坦",
      chinesePhoneticize: "tajikesitan",
      commonName: "Tajikistan",
      disablePrefill: false,
      displayName: "塔吉克斯坦",
      enable: true,
      formalName: "Republic of Tajikistan",
      id: "TJ",
      localName: "",
      nationalFlag: "🇹🇯",
      startChar: "T",
      telephoneCode: "992",
    },
    {
      chineseName: "汤加",
      chinesePhoneticize: "tangjia",
      commonName: "Tonga",
      disablePrefill: false,
      displayName: "汤加",
      enable: true,
      formalName: "Kingdom of Tonga",
      id: "TO",
      localName: "",
      nationalFlag: "🇹🇴",
      startChar: "T",
      telephoneCode: "676",
    },
    {
      chineseName: "坦桑尼亚",
      chinesePhoneticize: "tansangniya",
      commonName: "Tanzania",
      disablePrefill: false,
      displayName: "坦桑尼亚",
      enable: true,
      formalName: "United Republic of Tanzania",
      id: "TZ",
      localName: "",
      nationalFlag: "🇹🇿",
      startChar: "T",
      telephoneCode: "255",
    },
    {
      chineseName: "特克斯和凯科斯群岛",
      chinesePhoneticize: "tekesihekaikesiqundao",
      commonName: "Turks and Caicos",
      disablePrefill: false,
      displayName: "特克斯和凯科斯群岛",
      enable: true,
      formalName: "Turks and Caicos",
      id: "TC",
      localName: "",
      nationalFlag: "🇹🇨",
      startChar: "T",
      telephoneCode: "1",
    },
    {
      chineseName: "特里尼达和多巴哥",
      chinesePhoneticize: "telinidaheduobage",
      commonName: "Trinidad and Tobago",
      disablePrefill: false,
      displayName: "特里尼达和多巴哥",
      enable: true,
      formalName: "Republic of Trinidad and Tobago",
      id: "TT",
      localName: "",
      nationalFlag: "🇹🇹",
      startChar: "T",
      telephoneCode: "1868",
    },
    {
      chineseName: "土耳其",
      chinesePhoneticize: "tuerqi",
      commonName: "Turkey",
      disablePrefill: false,
      displayName: "土耳其",
      enable: true,
      formalName: "Republic of Turkey",
      id: "TR",
      localName: "",
      nationalFlag: "🇹🇷",
      startChar: "T",
      telephoneCode: "90",
    },
    {
      chineseName: "土库曼斯坦",
      chinesePhoneticize: "tukumansitan",
      commonName: "Turkmenistan",
      disablePrefill: false,
      displayName: "土库曼斯坦",
      enable: true,
      formalName: "",
      id: "TM",
      localName: "",
      nationalFlag: "🇹🇲",
      startChar: "T",
      telephoneCode: "993",
    },
    {
      chineseName: "突尼斯",
      chinesePhoneticize: "tunisi",
      commonName: "Tunisia",
      disablePrefill: false,
      displayName: "突尼斯",
      enable: true,
      formalName: "Tunisian Republic",
      id: "TN",
      localName: "",
      nationalFlag: "🇹🇳",
      startChar: "T",
      telephoneCode: "216",
    },
    {
      chineseName: "图瓦卢",
      chinesePhoneticize: "tuwalu",
      commonName: "Tuvalu",
      disablePrefill: false,
      displayName: "图瓦卢",
      enable: true,
      formalName: "",
      id: "TV",
      localName: "",
      nationalFlag: "🇹🇻",
      startChar: "T",
      telephoneCode: "688",
    },
  ],
  W: [
    {
      chineseName: "瓦努阿图",
      chinesePhoneticize: "wanuatu",
      commonName: "Vanuatu",
      disablePrefill: false,
      displayName: "瓦努阿图",
      enable: true,
      formalName: "Republic&nbsp;of&nbsp;Vanuatu",
      id: "VU",
      localName: "",
      nationalFlag: "🇻🇺",
      startChar: "V",
      telephoneCode: "678",
    },
    {
      chineseName: "危地马拉",
      chinesePhoneticize: "weidimala",
      commonName: "Guatemala",
      disablePrefill: false,
      displayName: "危地马拉",
      enable: true,
      formalName: "Republic of Guatemala",
      id: "GT",
      localName: "",
      nationalFlag: "🇬🇹",
      startChar: "G",
      telephoneCode: "502",
    },
    {
      chineseName: "委内瑞拉",
      chinesePhoneticize: "weineiruila",
      commonName: "Venezuela",
      disablePrefill: false,
      displayName: "委内瑞拉",
      enable: true,
      formalName: "Bolivarian&nbsp;Republic&nbsp;of&nbsp;Venezuela",
      id: "VE",
      localName: "",
      nationalFlag: "🇻🇪",
      startChar: "V",
      telephoneCode: "58",
    },
    {
      chineseName: "文莱",
      chinesePhoneticize: "wenlai",
      commonName: "Brunei",
      disablePrefill: false,
      displayName: "文莱",
      enable: true,
      formalName: "Negara Brunei Darussalam",
      id: "BN",
      localName: "",
      nationalFlag: "🇧🇳",
      startChar: "B",
      telephoneCode: "673",
    },
    {
      chineseName: "乌干达",
      chinesePhoneticize: "wuganda",
      commonName: "Uganda",
      disablePrefill: false,
      displayName: "乌干达",
      enable: true,
      formalName: "Republic&nbsp;of&nbsp;Uganda",
      id: "UG",
      localName: "",
      nationalFlag: "🇺🇬",
      startChar: "U",
      telephoneCode: "256",
    },
    {
      chineseName: "乌克兰",
      chinesePhoneticize: "wukelan",
      commonName: "Ukraine",
      disablePrefill: false,
      displayName: "乌克兰",
      enable: true,
      formalName: "",
      id: "UA",
      localName: "",
      nationalFlag: "🇺🇦",
      startChar: "U",
      telephoneCode: "380",
    },
    {
      chineseName: "乌拉圭",
      chinesePhoneticize: "wulagui",
      commonName: "Uruguay",
      disablePrefill: false,
      displayName: "乌拉圭",
      enable: true,
      formalName: "Oriental Republic of Uruguay",
      id: "UY",
      localName: "",
      nationalFlag: "🇺🇾",
      startChar: "U",
      telephoneCode: "598",
    },
    {
      chineseName: "乌兹别克斯坦",
      chinesePhoneticize: "wuzibiekesitan",
      commonName: "Uzbekistan",
      disablePrefill: false,
      displayName: "乌兹别克斯坦",
      enable: true,
      formalName: "Republic of Uzbekistan",
      id: "UZ",
      localName: "",
      nationalFlag: "🇺🇿",
      startChar: "U",
      telephoneCode: "998",
    },
  ],
  X: [
    {
      chineseName: "新西兰",
      chinesePhoneticize: "xinxilan",
      commonName: "New Zealand",
      disablePrefill: false,
      displayName: "新西兰",
      enable: true,
      formalName: "",
      id: "NZ",
      localName: "",
      nationalFlag: "🇳🇿",
      startChar: "N",
      telephoneCode: "64",
    },
    {
      chineseName: "香港",
      chinesePhoneticize: "xianggang",
      commonName: "Hong Kong",
      disablePrefill: false,
      displayName: "中国香港",
      enable: true,
      formalName: "Hong&nbsp;Kong&nbsp;Special&nbsp;Administrative&nbsp;Region",
      id: "HK",
      localName: "",
      nationalFlag: "🇭🇰",
      startChar: "H",
      telephoneCode: "852",
    },
    {
      chineseName: "象牙海岸",
      chinesePhoneticize: "xiangyahaian",
      commonName: "Cote d´Ivoire (Ivory Coast)",
      disablePrefill: false,
      displayName: "象牙海岸",
      enable: true,
      formalName: "Republic&nbsp;of&nbsp;Cote&nbsp;d&acute;Ivoire",
      id: "CI",
      localName: "",
      nationalFlag: "🇨🇮",
      startChar: "C",
      telephoneCode: "225",
    },
    {
      chineseName: "西班牙",
      chinesePhoneticize: "xibanya",
      commonName: "Spain",
      disablePrefill: false,
      displayName: "西班牙",
      enable: true,
      formalName: "Kingdom of Spain",
      id: "ES",
      localName: "",
      nationalFlag: "🇪🇸",
      startChar: "S",
      telephoneCode: "34",
    },
    {
      chineseName: "希腊",
      chinesePhoneticize: "xila",
      commonName: "Greece",
      disablePrefill: false,
      displayName: "希腊",
      enable: true,
      formalName: "Hellenic Republic",
      id: "GR",
      localName: "",
      nationalFlag: "🇬🇷",
      startChar: "G",
      telephoneCode: "30",
    },
    {
      chineseName: "新加坡",
      chinesePhoneticize: "xinjiapo",
      commonName: "Singapore",
      disablePrefill: false,
      displayName: "新加坡",
      enable: true,
      formalName: "Republic of Singapore",
      id: "SG",
      localName: "",
      nationalFlag: "🇸🇬",
      startChar: "S",
      telephoneCode: "65",
    },
    {
      chineseName: "新喀里多尼亚",
      chinesePhoneticize: "xinkaliduoniya",
      commonName: "New Caledonia",
      disablePrefill: false,
      displayName: "新喀里多尼亚",
      enable: true,
      formalName: "New Caledonia",
      id: "NC",
      localName: "",
      nationalFlag: "🇳🇨",
      startChar: "N",
      telephoneCode: "687",
    },
    {
      chineseName: "匈牙利",
      chinesePhoneticize: "xiongyali",
      commonName: "Hungary",
      disablePrefill: false,
      displayName: "匈牙利",
      enable: true,
      formalName: "Republic of Hungary",
      id: "HU",
      localName: "",
      nationalFlag: "🇭🇺",
      startChar: "H",
      telephoneCode: "36",
    },
    {
      chineseName: "叙利亚",
      chinesePhoneticize: "xuliya",
      commonName: "Syria",
      disablePrefill: false,
      displayName: "叙利亚",
      enable: false,
      formalName: "Syrian Arab Republic",
      id: "SY",
      localName: "",
      nationalFlag: "🇸🇾",
      startChar: "S",
      telephoneCode: "963",
    },
  ],
  Y: [
    {
      chineseName: "牙买加",
      chinesePhoneticize: "yamaijia",
      commonName: "Jamaica",
      disablePrefill: false,
      displayName: "牙买加",
      enable: true,
      formalName: "",
      id: "JM",
      localName: "",
      nationalFlag: "🇯🇲",
      startChar: "J",
      telephoneCode: "1876",
    },
    {
      chineseName: "亚美尼亚",
      chinesePhoneticize: "yameiniya",
      commonName: "Armenia",
      disablePrefill: false,
      displayName: "亚美尼亚",
      enable: true,
      formalName: "Republic of Armenia",
      id: "AM",
      localName: "",
      nationalFlag: "🇦🇲",
      startChar: "A",
      telephoneCode: "374",
    },
    {
      chineseName: "也门",
      chinesePhoneticize: "yemen",
      commonName: "Yemen",
      disablePrefill: false,
      displayName: "也门",
      enable: true,
      formalName: "Republic of Yemen",
      id: "YE",
      localName: "",
      nationalFlag: "🇾🇪",
      startChar: "Y",
      telephoneCode: "967",
    },
    {
      chineseName: "意大利",
      chinesePhoneticize: "yidali",
      commonName: "Italy",
      disablePrefill: false,
      displayName: "意大利",
      enable: true,
      formalName: "Italian Republic",
      id: "IT",
      localName: "",
      nationalFlag: "🇮🇹",
      startChar: "I",
      telephoneCode: "39",
    },
    {
      chineseName: "伊拉克",
      chinesePhoneticize: "yilake",
      commonName: "Iraq",
      disablePrefill: false,
      displayName: "伊拉克",
      enable: true,
      formalName: "Republic&nbsp;of&nbsp;Iraq",
      id: "IQ",
      localName: "",
      nationalFlag: "🇮🇶",
      startChar: "I",
      telephoneCode: "964",
    },
    {
      chineseName: "伊朗",
      chinesePhoneticize: "yilang",
      commonName: "Iran",
      disablePrefill: false,
      displayName: "伊朗",
      enable: false,
      formalName: "Islamic Republic of Iran",
      id: "IR",
      localName: "",
      nationalFlag: "🇮🇷",
      startChar: "I",
      telephoneCode: "98",
    },
    {
      chineseName: "印度",
      chinesePhoneticize: "yindu",
      commonName: "India",
      disablePrefill: false,
      displayName: "印度",
      enable: true,
      formalName: "Republic of India",
      id: "IN",
      localName: "",
      nationalFlag: "🇮🇳",
      startChar: "I",
      telephoneCode: "91",
    },
    {
      chineseName: "印度尼西亚",
      chinesePhoneticize: "yindunixiya",
      commonName: "Indonesia",
      disablePrefill: false,
      displayName: "印度尼西亚",
      enable: true,
      formalName: "Republic of Indonesia",
      id: "ID",
      localName: "",
      nationalFlag: "🇮🇩",
      startChar: "I",
      telephoneCode: "62",
    },
    {
      chineseName: "英国",
      chinesePhoneticize: "yingguo",
      commonName: "United Kingdom",
      disablePrefill: false,
      displayName: "英国",
      enable: true,
      formalName: "United Kingdom of Great Britain and Northern Ireland",
      id: "GB",
      localName: "",
      nationalFlag: "🇬🇧",
      startChar: "U",
      telephoneCode: "44",
    },
    {
      chineseName: "英属维尔京群岛",
      chinesePhoneticize: "yingshuweierjingqundao",
      commonName: "British Virgin Islands",
      disablePrefill: false,
      displayName: "英属维尔京群岛",
      enable: true,
      formalName: "",
      id: "VG",
      localName: "",
      nationalFlag: "🇻🇬",
      startChar: "B",
      telephoneCode: "1284",
    },
    {
      chineseName: "英属直布罗陀",
      chinesePhoneticize: "yingshuzhibuluotuo",
      commonName: "Gibraltar",
      disablePrefill: false,
      displayName: "英属直布罗陀",
      enable: true,
      formalName: "The British Overseas Territory of Gibraltar",
      id: "GI",
      localName: "",
      nationalFlag: "🇬🇮",
      startChar: "G",
      telephoneCode: "350",
    },
    {
      chineseName: "以色列",
      chinesePhoneticize: "yiselie",
      commonName: "Israel",
      disablePrefill: false,
      displayName: "以色列",
      enable: true,
      formalName: "State of Israel",
      id: "IL",
      localName: "",
      nationalFlag: "🇮🇱",
      startChar: "I",
      telephoneCode: "972",
    },
    {
      chineseName: "约旦",
      chinesePhoneticize: "yuedan",
      commonName: "Jordan",
      disablePrefill: false,
      displayName: "约旦",
      enable: true,
      formalName: "Hashemite Kingdom of Jordan",
      id: "JO",
      localName: "",
      nationalFlag: "🇯🇴",
      startChar: "J",
      telephoneCode: "962",
    },
    {
      chineseName: "越南",
      chinesePhoneticize: "yuenan",
      commonName: "Vietnam",
      disablePrefill: false,
      displayName: "越南",
      enable: true,
      formalName: "Socialist Republic of Vietnam",
      id: "VN",
      localName: "",
      nationalFlag: "🇻🇳",
      startChar: "V",
      telephoneCode: "84",
    },
  ],
  Z: [
    {
      chineseName: "赞比亚",
      chinesePhoneticize: "zanbiya",
      commonName: "Zambia",
      disablePrefill: false,
      displayName: "赞比亚",
      enable: true,
      formalName: "Republic of Zambia",
      id: "ZM",
      localName: "",
      nationalFlag: "🇿🇲",
      startChar: "Z",
      telephoneCode: "260",
    },
    {
      chineseName: "泽西岛",
      chinesePhoneticize: "zexidao",
      commonName: "Jersey",
      disablePrefill: false,
      displayName: "泽西岛",
      enable: true,
      formalName: "Bailiwick of Jersey",
      id: "JE",
      localName: "",
      nationalFlag: "🇯🇪",
      startChar: "J",
      telephoneCode: "44",
    },
    {
      chineseName: "乍得",
      chinesePhoneticize: "zhade",
      commonName: "Chad",
      disablePrefill: false,
      displayName: "乍得",
      enable: true,
      formalName: "Republic of Chad",
      id: "TD",
      localName: "",
      nationalFlag: "🇹🇩",
      startChar: "C",
      telephoneCode: "235",
    },
    {
      chineseName: "智利",
      chinesePhoneticize: "zhili",
      commonName: "Chile",
      disablePrefill: false,
      displayName: "智利",
      enable: true,
      formalName: "Republic of Chile",
      id: "CL",
      localName: "",
      nationalFlag: "🇨🇱",
      startChar: "C",
      telephoneCode: "56",
    },
    {
      chineseName: "中非共和国",
      chinesePhoneticize: "zhongfeigongheguo",
      commonName: "Central African Republic",
      disablePrefill: false,
      displayName: "中非共和国",
      enable: true,
      formalName: "null",
      id: "CF",
      localName: "",
      nationalFlag: "🇨🇫",
      startChar: "C",
      telephoneCode: "236",
    },
    {
      chineseName: "中国",
      chinesePhoneticize: "zhongguo",
      commonName: "China",
      disablePrefill: false,
      displayName: "中国",
      enable: true,
      formalName: "People´s Republic of China",
      id: "CN",
      localName: "",
      nationalFlag: "🇨🇳",
      startChar: "C",
      telephoneCode: "86",
    },
  ],
};
